server:
  port: 8020

spring:
  application:
    name: menu
  datasource:
    name: cc
    username: root
    password: 123
    url: jdbc:mysql://localhost:3306/cc?useUnicode=true&amp;characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.lxqlll.entity

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true